### ISSUE TITLE
Js Scope - Coding

### ISSUE THREAD

**Issue by francinelucca** [ibm-telemetry/telemetry-js#192]
```[tasklist]
### Tasks
- [ ] https://github.com/ibm-telemetry/telemetry-js/issues/193
- [ ] https://github.com/ibm-telemetry/telemetry-js/issues/196
- [ ] https://github.com/ibm-telemetry/telemetry-js/issues/197
```

**Comment by francinelucca** [comment]
🎉
