### ISSUE TITLE
Infrastructure: Local logging

### ISSUE THREAD

**Issue by francinelucca** [ibm-telemetry/telemetry-js#27]
### Summary

We need to setup logging for debug purposes, this encompasses determining a library (i.e. Winston) to use or writing code to handle file writing, writing error and debug APIs, setting up some decorator functions to handle 2 and finally writing up some unit tests to ensure correct behavior

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/26
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/29
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/28
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/32
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/30
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/31
```
