### ISSUE TITLE
Infrastructure: Unit test framework

### ISSUE THREAD

**Issue by jharvey10** [ibm-telemetry/telemetry-js#35]
### Summary

- [x] Install vitest
- [x] Configure vitest to generate code coverage reports
  - [x] This possibly means installing/configuring c8
- [x] Create unit test directory
- [x] Create fixture/resource directory (optional)

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/41
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/42
```
