### ISSUE TITLE
NPM scope

### ISSUE THREAD

**Issue by francinelucca** [ibm-telemetry/telemetry-js#37]
**Summary**

Ref: https://github.com/carbon-design-system/telemetrics-internal/blob/main/tech-designs/td-06-npm-scope.md

```[tasklist]
### Tasks
- [x] NPM scope - Install and configure relevant tooling to assist with package.json data capture
- [x] NPM scope - Develop npm file and filesystem analysis logic
- [x] NPM scope - "Plug" into emitter infrastructure to perform logging and event emission
- [x] NPM scope - Unit testing
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/50
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/51
```
