### ISSUE TITLE
Node.js emitter

### ISSUE THREAD

**Issue by mattrosno** [ibm-telemetry/telemetry-js#68]
### Summary

The telemetrics project is made up of:

- Many _emitters_ that understand code and design files, generate telemetry events, and send those events to the collector
- A _collector_ that gathers standardized telemetry events and sends them to the base
- A _base_ which is the server that holds onto the telemetry data

This first epic is for the Node.js emitter which understands npm projects and generates telemetry events.

### Intended outcome

This epic tracks the effort to reach feature parity with the legacy Carbon Telemetry code package ([@carbon/telemetry](https://www.npmjs.com/package/@carbon/telemetry).) That requires completion of the npm scope, where additional scopes like JSX and SCSS can come after.

Since this is the first epic, it also includes project tasks such as repository and dev-ops setup, testing, logging, etc.

### How will it work?

Instrumenting a project to track its metrics will require:

1. Generating an identifier for the project
2. Adding the telemetrics development dependency and adding the postinstall script
3. Configuring which metrics will be collected for the project

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/27
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/35
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/37
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/70
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/71
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/72
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/73
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/74
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/75
- [ ] https://github.com/carbon-design-system/telemetrics-js/issues/76
- [ ] https://github.com/ibm-telemetry/telemetry-js/issues/143
```
