### ISSUE TITLE
JSX scope

### ISSUE THREAD

**Issue by mattrosno** [ibm-telemetry/telemetry-js#69]
```[tasklist]
### Tasks
- [ ] https://github.com/ibm-telemetrics/telemetrics-js/issues/91
- [ ] https://github.com/ibm-telemetrics/telemetrics-js/issues/96
- [ ] https://github.com/ibm-telemetrics/telemetrics-js/issues/99
- [ ] https://github.com/ibm-telemetrics/telemetrics-js/issues/100
- [ ] https://github.com/ibm-telemetrics/telemetrics-js/issues/98
- [ ] https://github.com/ibm-telemetrics/telemetrics-js/issues/101
```
