### ISSUE TITLE
Open source this repo!

### ISSUE THREAD

**Issue by jdharvey-ibm** [ibm-telemetry/telemetry-js#97]
```[tasklist]
### Tasks
- [x] Add DCO Bot
- [x] Onboard to SonarCloud
- [x] verify code of conduct
- [x] verify license
- [x] verify contributing
- [x] make actual readme
```
